# ~/.config/starship.toml
# Minimal Starship Configuration - Solarized Theme
# Clean prompt: user@host ~/directory $

# Global prompt configuration - minimal elements only
format = """
$username\
$hostname\
$directory\
$jobs\
$battery\
$status\
$character"""  # Removed trailing space here

add_newline = false  # No blank line between commands

# Timeout for commands (milliseconds)
command_timeout = 500

# Directory module - always shown
[directory]
truncation_length = 3
truncate_to_repo = true
format = "[](fg:#93A1A1)[:](fg:#93A1A1)[$path]($style)"  # Solarized base1 grey colon
style = "fg:#B58900"  # Solarized yellow/golden
read_only = " 🔒"
truncation_symbol = "…/"
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Character - prompt symbol
[character]
success_symbol = "[❯](fg:#93A1A1)"  # Solarized base1 grey
error_symbol = "[❯](fg:#DC322F)"  # Solarized red for errors
vimcmd_symbol = "[❮](fg:#93A1A1)"  # Solarized base1 grey
format = "$symbol "  # Explicitly set format with single space

# Username - only show when not your usual user
[username]
style_user = "fg:#268BD2"  # Solarized blue
style_root = "fg:#DC322F"  # Solarized red
format = "[$user]($style)"  # User stays colored
disabled = false
show_always = true

# Hostname - only show when SSH'd
[hostname]
ssh_only = true
format = "[](fg:#93A1A1)[@](fg:#93A1A1)[$hostname]($style)"  # Grey @
style = "fg:#2AA198"  # Solarized cyan
disabled = false

# Battery - only show when low
[battery]
full_symbol = "🔋"
charging_symbol = "⚡"
discharging_symbol = "💀"
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = "fg:#DC322F"  # Solarized red

# Jobs - background jobs indicator
[jobs]
symbol = "✦ "
number_threshold = 1
format = "[$symbol$number]($style) "
style = "fg:#B58900"  # Solarized yellow

# Status - exit code of last command
[status]
style = "fg:#DC322F"  # Solarized red
symbol = "✖ "
format = '[$symbol$status]($style) '
disabled = true  # Enable if you want to see exit codes
